using System;
using System.Collections.Generic;
using System.Linq;
using Domain;
using IBusinessLogic;
using IDataAccess;

namespace BusinessLogic 
{

    public class PlayerBL : IPlayerBL
    {

        private readonly IRepository<Category> categoryRepository;

        private readonly IRepository<PlayableContent> contentRepository;

        private readonly IRepository<Playlist> playlistRepository;

        public PlayerBL(IRepository<Category> categoryRepository,
                        IRepository<PlayableContent> contentRepository,
                        IRepository<Playlist> playlistRepository)
        {
            this.categoryRepository = categoryRepository;
            this.contentRepository = contentRepository;
            this.playlistRepository = playlistRepository;
        }

        public List<Category> GetCategories()
        {
            return categoryRepository.GetAll().ToList();
        }

        public List<CategoryElement> GetCategoryElements(int categoryId)
        {
            var playlists = playlistRepository.GetAll().ToList();
            var contents = contentRepository.GetAll().ToList();
            List<CategoryElement> auxReturn = new List<CategoryElement>();

            foreach (Playlist p in playlists)
            {
                if (p.Category.Id == categoryId) auxReturn.Add(p);
            }

            foreach (PlayableContent c in contents)
            {
                if (c.Category.Id == categoryId) auxReturn.Add(c);
            }

            return auxReturn;
        }

        public Playlist GetPlaylist(int playlistId)
        {
            if (playlistId > 0) 
            {
                return playlistRepository.Get(playlistId);
            }
            else
            {
                throw new Exception("No playlist associated to given id.");
            }
        }

        public PlayableContent GetPlayableContent(int contentId)
        {
            if (contentId <= contentRepository.GetAll().ToList().Count() && contentId > 0)
            {
                return contentRepository.Get(contentId);
            }
            else throw new Exception("No content associated to given id.");
        }

        public void ValidateContent (PlayableContent content)
        {
            if(content.Id != 0)
            {
                throw new Exception("Do not hardcode contentId, it is an autogenerated value.");
            }
            foreach (PlayableContent auxContent in contentRepository.GetAll().ToList())
            {
                if (content.Name == auxContent.Name &&  content.Author == auxContent.Author)
                {

                    throw new Exception($"The content you are trying to create already exists at index {auxContent.Id}");
                }
            }
        }

        public PlayableContent AddIndependentContent (PlayableContent content)
        {
            ValidateContent(content);
            contentRepository.Add(content);
            return contentRepository.Get(contentRepository.GetAll().ToList().Count());
        }

        public void ExistsPlaylist(Playlist playlist)
        {
            Playlist p = GetPlaylist(playlist.Id);
            if (GetPlaylist(playlist.Id) != null)
            {
                throw new Exception("The playlist you are trying to create already exists.");
            }
        }

        public void ValidId(int id)
        {
            if (id <= 0)
            {
                throw new Exception("Invalid id");
            }
        }

        public void AddPlaylist (Playlist playlist)
        {
            ExistsPlaylist(playlist);
            ValidId(playlist.Id);
            ValidId(playlist.CategoryId);
            playlistRepository.Add(playlist);
        }

        public void AlreadyOnPlaylist (Playlist playlist, PlayableContent content)
        {
            if (playlist.Contents.Contains(content))
            {
                throw new Exception("The playable content inserted already exists in the playlist.");
            }
        }

        public void PlaylistExists(Playlist playlist)
        {
            
            if (!playlistRepository.GetAll().ToList().Contains(playlist))
            {
                playlistRepository.Add(playlist);
            }
        }

        public void ContentExists(PlayableContent content)
        {
            PlayableContent auxContent = contentRepository.Get(content.Id);
            if (auxContent == null)
            {
                contentRepository.Add(auxContent);
            } 
        }

        public void SameCategory(Playlist playlist, PlayableContent content)
        {
            if (playlist.Category != content.Category)
            {
                throw new Exception("This playable content cannot be added to the playlist.");
            }
        }

        public void AddContentToPlaylist (Playlist playlist, PlayableContent content)
        {
            SameCategory(playlist, content);
            ContentExists(content);
            PlaylistExists(playlist);
            AlreadyOnPlaylist(playlist, content);
            //Playlist auxPlaylist = playlistRepository.Get(playlist.Id);
            //PlayableContent auxContent = contentRepository.Get(content.Id);
            playlist.Contents.Add(content);
        }

        public void DeleteContent (int contentId)
        {
            if (contentId <= contentRepository.GetAll().ToList().FindLast(x => x.Id != 0).Id && contentId > 0)
            {
                contentRepository.Delete(contentId);
            }
            else throw new Exception("No content associated to given id.");
        }

        public void RemoveContentsFromPlaylist(int playlistId)
        {
            Playlist playlist = GetPlaylist(playlistId);

            if (playlist.Contents.ToList().Count != 0)
            {
                foreach (PlayableContent content in playlist.Contents)
                {
                    playlist.Contents.ToList().Remove(content);
                }
            }
        }

        public void DeletePlaylist(int playlistId)
        {
            RemoveContentsFromPlaylist(playlistId);
            playlistRepository.Delete(playlistId);
        }

    }
        
}
